In [31]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [32]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv')
df

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
...,...,...
49995,I thought this movie did a down right good job...,positive
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative
49997,I am a Catholic taught in parochial elementary...,negative
49998,I'm going to have to disagree with the previou...,negative


In [33]:
df.tail(20)

,review,sentiment
49980,A stunning film of high quality.<br /><br />Ap...,positive
49981,"And I repeat, please do not see this movie! Th...",negative
49982,"To be hones, I used to like this show and watc...",negative
49983,"I loved it, having been a fan of the original ...",positive
49984,Hello it is I Derrick Cannon and I welcome you...,negative
49985,Imaginary Heroes is clearly the best film of t...,positive
49986,This movie is a disgrace to the Major League F...,negative
49987,A remake of Alejandro Amenabar's Abre los Ojos...,negative
49988,"When I first tuned in on this morning news, I ...",negative
49989,I got this one a few weeks ago and love it! It...,positive


In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [35]:
df.duplicated().sum().item()

418

In [36]:
df.drop_duplicates(subset=['review'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)
df.head(20)

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
5,"Probably my all-time favorite movie, a story o...",positive
6,I sure would like to see a resurrection of a u...,positive
7,"This show was an amazing, fresh & innovative i...",negative
8,Encouraged by the positive comments about this...,negative
9,If you like original gut wrenching laughter yo...,positive


In [37]:
df["review"] = df["review"].str.lower()
df["review"] = df["review"].str.replace(r"<.*?>", "", regex=True)

In [38]:
df.head()

,review,sentiment
0,one of the other reviewers has mentioned that ...,positive
1,a wonderful little production. the filming tec...,positive
2,i thought this was a wonderful way to spend ti...,positive
3,basically there's a family where a little boy ...,negative
4,"petter mattei's ""love in the time of money"" is...",positive


In [39]:
X=df["review"]
y=df["sentiment"]

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=61)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
vectorizer = CountVectorizer(
    lowercase=True, 
    stop_words='english',
    ngram_range=(1, 2),
    token_pattern=r'\b[a-zA-Z]{3,}\b', 
    min_df=5,
)
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [43]:
vectorizer.vocabulary_

{'working': 102285,
 'way': 99967,
 'collection': 15198,
 'lugosi': 55560,
 'films': 32689,
 'recently': 75202,
 'having': 40847,
 'just': 47305,
 'blown': 8733,
 'away': 5066,
 'couple': 17542,
 'days': 19351,
 'ago': 2181,
 'combination': 15322,
 'boris': 9356,
 'karloff': 48217,
 'black': 8343,
 'cat': 12005,
 'really': 74480,
 'looking': 54381,
 'forward': 34261,
 'seeing': 81136,
 'collaboration': 15178,
 'raven': 73976,
 'alas': 2409,
 'didn': 21356,
 'work': 102056,
 'end': 25956,
 'film': 30768,
 'quite': 73252,
 'disappointed': 22329,
 'quarters': 73108,
 'movie': 60535,
 'thought': 92285,
 'story': 87380,
 'lacked': 49840,
 'real': 74161,
 'suspense': 89679,
 'doing': 23396,
 'pretty': 71612,
 'good': 37473,
 'job': 46706,
 'holding': 42293,
 'things': 91627,
 'somewhat': 85109,
 'mad': 55729,
 'sort': 85391,
 'surgical': 89525,
 'genius': 35900,
 'falls': 29154,
 'love': 55021,
 'young': 103643,
 'woman': 101517,
 'irene': 45777,
 'ware': 99011,
 'treats': 94620,
 'car': 113

In [44]:
vectorizer.get_feature_names_out().tolist()[:20]

['aaa',
 'aag',
 'aaliyah',
 'aamir',
 'aamir khan',
 'aardman',
 'aaron',
 'aaron carter',
 'aaron eckhart',
 'aaron sorkin',
 'aback',
 'abandon',
 'abandoned',
 'abandoned building',
 'abandoned church',
 'abandoned film',
 'abandoned house',
 'abandoned school',
 'abandoning',
 'abandonment']

In [45]:
y.unique()

array(['positive', 'negative'], dtype=object)

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [47]:
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [48]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(solver='lbfgs',max_iter=1000,penalty='l2')
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [49]:
y_pred = model.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.8909579831932773


In [51]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[6597  855]
 [ 767 6656]]


In [52]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, target_names=['negative', 'positive'])
print(report)

              precision    recall  f1-score   support

    negative       0.90      0.89      0.89      7452
    positive       0.89      0.90      0.89      7423

    accuracy                           0.89     14875
   macro avg       0.89      0.89      0.89     14875
weighted avg       0.89      0.89      0.89     14875



In [53]:
y_0=df.groupby('sentiment').size()
y_0

,0
sentiment,
negative,24698
positive,24884


In [54]:
from sklearn.naive_bayes import MultinomialNB
modelnb = MultinomialNB(alpha=1.0)

In [55]:
modelnb.fit(X_train, y_train)
y_pred_nb = modelnb.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

In [57]:
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Accuracy: 0.8756302521008403
[[6558  894]
 [ 956 6467]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.88      7452
           1       0.88      0.87      0.87      7423

    accuracy                           0.88     14875
   macro avg       0.88      0.88      0.88     14875
weighted avg       0.88      0.88      0.88     14875

